version: '3.8'

networks:
  proxy_net:
    name: proxy_net
    driver: bridge

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp" # Shifted web UI to 8080 so NPM can use 80
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'SetYourSecurePasswordHere'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      - proxy_net

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'   # HTTP traffic
      - '443:443' # HTTPS traffic
      - '81:81'   # NPM Admin Web UI
    volumes:
      - './npm/data:/data'
      - './npm/letsencrypt:/etc/letsencrypt'
    restart: unless-stopped
    networks:
      - proxy_net