version: '3.8'

networks:
  proxy_net:
    external: true

services:
  amp:
    container_name: amp
    image: cubecoders/amp:latest
    ports:
      - "8081:8081"
      - "25565:25565"
    volumes:
      - ./amp/datastore:/home/amp/.ampdata
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
    networks:
      - proxy_net

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /mnt/synology/immich:/usr/src/app/upload
      - ./immich/cache:/usr/src/app/cache
    env_file:
      - .env
    environment:
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - REDIS_HOSTNAME=immich_redis
    ports:
      - "2283:2283"
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      - immich-database
      - immich-redis
    restart: unless-stopped
    networks:
      - proxy_net

  immich-database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    volumes:
      - ./immich/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - proxy_net

  immich-redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine
    restart: unless-stopped
    networks:
      - proxy_net