networks:
  proxy_net:
    external: true

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ./models:/root/.ollama
    ports:
      - "${VLAN11_IP}:11434:11434"
    restart: unless-stopped
    networks:
      - proxy_net

  open-webui:
    container_name: open_webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=false
    volumes:
      - ./open-webui:/app/backend/data
    ports:
      - "${VLAN11_IP}:3004:8080"
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - proxy_net
